version: 1.0.{build}
image: Visual Studio 2017
clone_depth: 1
build_script:
- cmd: dotnet build -c RELEASE
test_script:
- cmd: dotnet test _UnitTests\CoLib.Common.Test -c RELEASE
artifacts:
- path: '**\*.nupkg'
  name: Nuget Packages
deploy:
- provider: NuGet
  api_key:
    secure: oQiLxs4Z7o15Qi3/1XG3ObxqsuX5ofE4AFUifl8Ku4VhmYBmXu8Yg+Kj6GFgY6xA
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#builds'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
