version: 2.1.{build}
image: Visual Studio 2019
clone_depth: 1
build_script:
- cmd: dotnet build -c RELEASE
test_script:
- cmd: dotnet test CoLib.Common.Test -c RELEASE
artifacts:
- path: '**\*.nupkg'
  name: Nuget Packages
deploy:
- provider: NuGet
  api_key:
    secure: oQiLxs4Z7o15Qi3/1XG3ObxqsuX5ofE4AFUifl8Ku4VhmYBmXu8Yg+Kj6GFgY6xA
